# https://realm.github.io/SwiftLint/rule-directory.html
disabled_rules: # rule identifiers turned on by default to exclude from running
  - function_parameter_count
  - function_body_length
  - trailing_whitespace
  - force_cast
  - force_try

opt_in_rules: # some rules are turned off by default, so you need to opt-in

warning_threshold: 15

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - R.generated.swift
  - templates
  - VaporApp

line_length: 150

identifier_name:
  min_length: 2

